# -*- coding: utf-8 -*-
"""threshold_wrapper_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbGGxgXBcVbgJz0z1iUoVu10WMqZF4YD

# 🧠 Modelo Preditivo de Atraso de Voos com Threshold Encapsulado

### 📌 Descrição

Este projeto implementa um modelo preditivo de atraso de voos baseado em Random Forest, com a regra de decisão (threshold = 0.4) encapsulada no próprio modelo.

A encapsulação do threshold garante que a regra de negócio seja aplicada de forma consistente em produção, evitando dependência de lógica adicional no backend ou risco de inconsistência entre ambientes.

O modelo é exportado utilizando joblib e depende de um wrapper Python (ModeloComThreshold) definido como módulo importável, permitindo que o backend carregue o modelo sem erros de serialização.

### ⚙️ Como o Threshold é Aplicado

O modelo interno retorna probabilidades de atraso (predict_proba)

A classe ModeloComThreshold aplica a regra:

atraso = 1 se P(atraso) ≥ 0.4

atraso = 0 caso contrário

O método:

* predict_proba() → retorna probabilidades

* predict() → retorna a decisão final, já com threshold aplicado
"""

from sklearn.base import BaseEstimator, ClassifierMixin
import numpy as np

class ModeloComThreshold(BaseEstimator, ClassifierMixin):
    def __init__(self, modelo, threshold=0.4):
        self.modelo = modelo
        self.threshold = threshold

        if hasattr(modelo, "classes_"):
            self.classes_ = modelo.classes_

    def predict(self, X):
        if not hasattr(self.modelo, "predict_proba"):
            raise AttributeError("O modelo interno não suporta predict_proba")

        prob_atraso = self.modelo.predict_proba(X)[:, 1]
        return (prob_atraso >= self.threshold).astype(int)

    def predict_proba(self, X):
        return self.modelo.predict_proba(X)
