# -*- coding: utf-8 -*-
"""03_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WLJpQMKs3qN62SheyuzfBYu68pS9ykw

# 🌐  API Preditiva com FastAPI
"""

from fastapi import FastAPI
import joblib
import pandas as pd

app = FastAPI(title="FlightOnTime API")

model = joblib.load("flightontime_model.joblib")
THRESHOLD = 0.4

@app.post("/predict")
def predict_delay(data: dict):
    df = pd.DataFrame([data])

    proba = model.predict_proba(df)[0][1]
    prediction = int(proba >= THRESHOLD)

    return {
        "atraso_previsto": prediction,
        "probabilidade_atraso": round(float(proba), 4),
        "threshold_utilizado": THRESHOLD
    }