# -*- coding: utf-8 -*-
"""03_app_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17M__I4od7X4IDLw9rAKqkgASi3tFV_R1

# 🌐 FlightOnTime API

Serviço de predição de atraso de voos usando FastAPI e modelo treinado.
"""

from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd
import joblib

# ================================
# Configurações
# ================================

import os
import gdown

MODEL_PATH = "flight_delay_model.pkl"
GDRIVE_ID = "1NEXByPViUZjgdKYMMBqZUtPHL4zd6h5x"

if not os.path.exists(MODEL_PATH):
    gdown.download(
        f"https://drive.google.com/uc?id={GDRIVE_ID}",
        MODEL_PATH,
        quiet=False
    )

model = joblib.load(MODEL_PATH)


THRESHOLD = 0.4

# ================================
# Inicialização da API
# ================================

app = FastAPI(
    title="FlightOnTime API",
    description="Serviço de predição de atraso de voos antes da decolagem",
    version="1.0.0"
)


# ================================
# Esquema de entrada
# ================================

class FlightInput(BaseModel):
    sigla_icao_aeroporto_origem: str
    sigla_icao_aeroporto_destino: str
    sigla_icao_empresa_aerea: str
    pais_origem: str
    codigo_tipo_linha: str
    modelo_equipamento: str
    numero_de_assentos: int
    hora_partida_prevista_num: int
    periodo_dia_calc: str
    is_weekend: int
    rota: str
    mes: int
    dia_semana: int

# ================================
# Endpoint de predição
# ================================

@app.post("/predict")
def predict_delay(flight: FlightInput):

    input_df = pd.DataFrame([flight.dict()])

    prob_atraso = model.predict_proba(input_df)[0][1]
    atraso_previsto = int(prob_atraso >= THRESHOLD)

    return {
        "previsao": "Atrasado" if atraso_previsto else "Pontual",
        "probabilidade_atraso": round(prob_atraso, 4),
        "threshold_utilizado": THRESHOLD
    }

"""### Teste"""

teste = pd.DataFrame([{
    "sigla_icao_aeroporto_origem": "GIG",
    "sigla_icao_aeroporto_destino": "GRU",
    "sigla_icao_empresa_aerea": "AZUL",
    "pais_origem": "BR",
    "codigo_tipo_linha": "N",
    "modelo_equipamento": "A320",
    "numero_de_assentos": 180,
    "hora_partida_prevista_num": 14,
    "periodo_dia_calc": "TARDE",
    "is_weekend": 0,
    "rota": "GIG-GRU",
    "mes": 11,
    "dia_semana": 2
}])

model.predict_proba(teste)

"""### TESTE DA API (simulado no notebook)"""

payload = FlightInput(
    sigla_icao_aeroporto_origem="GIG",
    sigla_icao_aeroporto_destino="GRU",
    sigla_icao_empresa_aerea="AZUL",
    pais_origem="BR",
    codigo_tipo_linha="N",
    modelo_equipamento="A320",
    numero_de_assentos=180,
    hora_partida_prevista_num=14,
    periodo_dia_calc="TARDE",
    is_weekend=0,
    rota="GIG-GRU",
    mes=11,
    dia_semana=2
)

predict_delay(payload)